version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - lesson

  go-app:
    image: ryota1119/go-app:latest
    ports:
      - "4040:8080"
    depends_on:
      - dev-postgres
    env_file:
      - .env
    networks:
      - lesson

networks:
  lesson: