version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - lesson

  go-app:
    image: ryota1119/go-app:latest
    ports:
      - "4040:4040"
    depends_on:
      - dev-postgres
    environment:
      POSTGRES_HOST: dev-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: udemy
      POSTGRES_PW: udemy
      POSTGRES_DB: udemy
    networks:
      - lesson
  
networks:
  lesson: