name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source 
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          docker system prune -af
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME  }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ryota1119/go-app .
      - name: Push Docker image
        run: docker push ryota1119/go-app  
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull ryota1119/go-app:latest
      - name: Delete old container
        run: docker rm -f go-app-container
      - name: Stop and remove existing containers
        run: docker compose down || true

      - name: Start containers with docker-compose
        run: docker-compose up -d --remove-orphans