name: Deploy with Docker Compose
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PW=${{ secrets.POSTGRES_PW }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "SECRET=${{ secrets.SECRET }}" >> .env
          echo "GO_ENV=${{ secrets.GO_ENV }}" >> .env
          echo "API_DOMAIN=${{ secrets.API_DOMAIN }}" >> .env
          echo "FE_URL=${{ secrets.FE_URL }}" >> .env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest image
        run: docker pull ryota1119/go-app:latest

      - name: Stop and remove existing containers
        run: docker compose down || true

      - name: Start containers with docker-compose
        run: docker compose up -d --remove-orphans